[package]
name = "anagram_solver"
version = "0.1.1"
edition = "2021"

[lib]
name = "anagram_solver"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10.3"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
